# Generated by Django 2.1.7 on 2019-02-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='signin_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SignIn'),
        ),
    ]
