# Generated by Django 2.1.7 on 2019-02-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190221_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='signin_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.SignIn'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
