# Generated by Django 2.1.7 on 2019-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190224_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='full_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
