# Generated by Django 2.1.7 on 2019-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190302_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='full_name',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
