# Generated by Django 2.1.7 on 2019-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190302_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='full_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
