# Generated by Django 2.1.7 on 2019-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20190302_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
