# Generated by Django 2.1.7 on 2019-03-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190302_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='signin_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.SignIn'),
        ),
    ]
