# Generated by Django 2.1.7 on 2019-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190305_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='user_details',
            field=models.ManyToManyField(to='login.SignIn'),
        ),
    ]
