# Generated by Django 2.1.7 on 2019-03-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_bookdetails_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='user_details',
        ),
        migrations.DeleteModel(
            name='bookDetails',
        ),
    ]
