# Generated by Django 2.1.7 on 2019-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190305_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, null=True)),
                ('user_details', models.ManyToManyField(to='login.SignIn')),
            ],
        ),
    ]
