# Generated by Django 2.1.7 on 2019-03-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_bookdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
